### ISSUE TITLE
Incus 6.1.0 - php json_decode

### ISSUE THREAD

**Issue by rajbock** [lxc/incus#872]
After updating to incus 6.1.0, I receive the following error message in my containers (Joomla Update Check):

2024-05-15T06:05:11+00:00       CRITICAL 1.2.3.4  error   Uncaught Throwable of type JsonException thrown with message "Syntax error". Stack trace: #0 [ROOT]/libraries/vendor/php-tuf/php-tuf/src/Metadata/MetadataBase.php(90): json_decode('', true, 512, 4194304)
#1 [ROOT]/libraries/vendor/php-tuf/php-tuf/src/Client/Repository.php(67): Tuf\Metadata\MetadataBase::createFromJson('')
#2 [ROOT]/libraries/vendor/php-tuf/php-tuf/src/Client/Updater.php(181): Tuf\Client\Repository->getTimestamp()
#3 [ROOT]/libraries/vendor/php-tuf/php-tuf/src/Client/Updater.php(148): Tuf\Client\Updater->updateTimestamp()
#4 [ROOT]/libraries/src/TUF/TufFetcher.php(117): Tuf\Client\Updater->refresh()

Downgrade to 6.0.0 and it works again.

**Comment by rajbock** [comment]
Ok, that seems to have been resolved. It was probably more due to Joomla and I noticed it right after the update to incus 6.1.0.
